name: savannamodel
version: '0.1.0.0'
synopsis: Savanna Model website builder
license: PublicDomain
author: David Parrish
maintainer: daveparrish@tutanota.com
extra-source-files:
  - package.yaml
  - stack.yaml
  - README

github: dmp1ce/savannamodel

ghc-options:
  - -O2
  - -Wall
  - -Wcompat
  - -Werror
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
executables:
  site:
    main: site.hs
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - base
      - hakyll
      - filepath
